import 'server-only';

/**
 * Throwaway-mail providers refused at sign-up. A modest list of the best-known ones (an operator
 * adds more with DISPOSABLE_EMAIL_DOMAINS); it raises the cost of farming sign-up bonuses, it does
 * not stop a determined person, and a provider missing here is simply not blocked. Never add a
 * mainstream mailbox provider: a false positive turns a real customer away.
 */
const BUILT_IN = [
  '10mail.org',
  '10minutemail.co.uk',
  '10minutemail.com',
  '10minutemail.net',
  '10minutemail.org',
  '20minutemail.com',
  '33mail.com',
  'anonbox.net',
  'anonymbox.com',
  'armyspy.com',
  'binkmail.com',
  'bobmail.info',
  'bugmenot.com',
  'burnermail.io',
  'byom.de',
  'chacuo.net',
  'cool.fr.nf',
  'courriel.fr.nf',
  'cuvox.de',
  'dayrep.com',
  'deadaddress.com',
  'despam.it',
  'devnullmail.com',
  'discard.email',
  'discardmail.com',
  'discardmail.de',
  'disposableemailaddresses.com',
  'dispostable.com',
  'dodgeit.com',
  'dontreg.com',
  'dropmail.me',
  'dumpmail.de',
  'e4ward.com',
  'easytrashmail.com',
  'einrot.com',
  'email60.com',
  'emailfake.com',
  'emailondeck.com',
  'emailtemporanea.com',
  'emailtemporar.ro',
  'emkei.cz',
  'fakeinbox.com',
  'fakemail.net',
  'fakemailgenerator.com',
  'filzmail.com',
  'fleckens.hu',
  'getairmail.com',
  'getnada.com',
  'grr.la',
  'guerrillamail.biz',
  'guerrillamail.com',
  'guerrillamail.de',
  'guerrillamail.info',
  'guerrillamail.net',
  'guerrillamail.org',
  'guerrillamailblock.com',
  'gustr.com',
  'haltospam.com',
  'harakirimail.com',
  'hidemail.de',
  'imails.info',
  'inboxalias.com',
  'inboxkitten.com',
  'incognitomail.org',
  'instant-mail.de',
  'jetable.fr.nf',
  'jetable.org',
  'jourrapide.com',
  'kasmail.com',
  'klzlk.com',
  'kurzepost.de',
  'lroid.com',
  'mail-temporaire.fr',
  'mail-temporary.com',
  'mail.tm',
  'mail7.io',
  'mailbucket.org',
  'mailcatch.com',
  'maildrop.cc',
  'maileater.com',
  'mailexpire.com',
  'mailforspam.com',
  'mailin8r.com',
  'mailinater.com',
  'mailinator.com',
  'mailinator.net',
  'mailinator2.com',
  'mailmoat.com',
  'mailnesia.com',
  'mailnull.com',
  'mailsac.com',
  'mailtemp.info',
  'mailtothis.com',
  'mailzilla.com',
  'meltmail.com',
  'mintemail.com',
  'minuteinbox.com',
  'moakt.cc',
  'moakt.com',
  'moakt.ws',
  'mohmal.com',
  'moncourrier.fr.nf',
  'monemail.fr.nf',
  'monmail.fr.nf',
  'mt2015.com',
  'mytemp.email',
  'mytrashmail.com',
  'nada.email',
  'nada.ltd',
  'nobulk.com',
  'noclickemail.com',
  'nospam.ze.tc',
  'nowmymail.com',
  'objectmail.com',
  'oneoffemail.com',
  'owlymail.com',
  'pookmail.com',
  'proxymail.eu',
  'punkass.com',
  'quickinbox.com',
  'rcpt.at',
  'rhyta.com',
  'safetymail.info',
  'sharklasers.com',
  'shieldemail.com',
  'spam.la',
  'spam4.me',
  'spamavert.com',
  'spambog.com',
  'spambox.us',
  'spamex.com',
  'spamgourmet.com',
  'spamhole.com',
  'spaml.com',
  'superrito.com',
  'teleworm.us',
  'temp-mail.io',
  'temp-mail.org',
  'temp-mail.ru',
  'tempail.com',
  'tempemail.net',
  'tempinbox.com',
  'tempmail.com',
  'tempmail.net',
  'tempmailaddress.com',
  'tempmailo.com',
  'tempr.email',
  'thankyou2010.com',
  'throwawaymail.com',
  'tmail.ws',
  'tmpeml.com',
  'tmpmail.net',
  'tmpmail.org',
  'trash-mail.com',
  'trashmail.at',
  'trashmail.com',
  'trashmail.de',
  'trashmail.io',
  'trashmail.me',
  'trashmail.net',
  'trashmail.org',
  'trashmail.ws',
  'trashmailer.com',
  'wegwerfmail.de',
  'wegwerfmail.net',
  'wegwerfmail.org',
  'yopmail.com',
  'yopmail.fr',
  'yopmail.net',
] as const;

export const BUILT_IN_DISPOSABLE_DOMAINS: ReadonlySet<string> = new Set(BUILT_IN);

/**
 * True when the address's domain, or a parent domain of it, is on the built-in list or in `extra`
 * (the operator's DISPOSABLE_EMAIL_DOMAINS, already lower-cased). `anything@x.mailinator.com`
 * counts as `mailinator.com`.
 */
export function isDisposableEmail(email: string, extra: readonly string[] = []): boolean {
  const at = email.lastIndexOf('@');
  if (at < 0) return false;
  const labels = email
    .slice(at + 1)
    .trim()
    .toLowerCase()
    .split('.');
  for (let start = 0; start < labels.length - 1; start += 1) {
    const candidate = labels.slice(start).join('.');
    if (BUILT_IN_DISPOSABLE_DOMAINS.has(candidate) || extra.includes(candidate)) return true;
  }
  return false;
}
