import 'server-only';
import {
  ART_WORDS_AR,
  ART_WORDS_EN,
  EDIT_VERBS_AR,
  GARMENT_OFF_EN,
  GARMENTS_EN,
  HATE_TARGETS_AR,
  HATE_TARGETS_AR_SINGULAR,
  HATE_TARGETS_EN,
  HATE_TARGETS_EN_SINGULAR,
  HATE_VERBS_AR,
  HATE_VERBS_EN,
  HATE_VERBS_WEAK_AR,
  HATE_VERBS_WEAK_EN,
  MINORS_AR,
  MINORS_EN,
  NUDITY_AR,
  NUDITY_EN,
  PEOPLE_AR,
  PEOPLE_EN,
  PERSON_CUES_EN,
  POSSESSED_GARMENTS_AR,
  PRONOUNS_EN,
  REAL_PERSON_CUES_EN,
  REMOVE_VERBS_AR,
  REMOVE_VERBS_EN,
  SEXUAL_ACT_WORDS_EN,
  SEXUAL_WIDE_AR,
  SEXUAL_WIDE_EN,
  SEX_ACT_AR,
  TOPLESS_SETTINGS_EN,
  unique,
} from './vocabulary';

/**
 * The built-in, deliberately modest moderation rules (English and Arabic). Everything is
 * data: add a term by adding a string. Terms are written naturally (any case, Arabic with or
 * without diacritics) and normalized when compiled, so `نيك` and `نِيك` are the same entry.
 *
 * Matching is by whole token, never by substring, so "Essex", "grape" or "Scunthorpe" do not
 * trip "sex", "rape" or anything else. A multi-word entry is a phrase of adjacent tokens. English
 * entries also match their plural (`+s`/`+es`); Arabic entries also match with the common
 * one-letter clitics and the article attached (`و ف ب ك ل`, `ال`, `لل`).
 *
 * Two kinds of rule exist:
 * - a term rule blocks a phrase on its own;
 * - a combo rule blocks when a word of set `a` and a word of set `b` sit within `window` tokens
 *   of each other (and, when it has a set `c`, a word of `c` sits that close to one of them too),
 *   which keeps ambiguous words ("naked", "child", "kill") harmless on their own and harmful in
 *   context. The word lists are in `vocabulary.ts`.
 *
 * Sexual content involving minors is the one category that is never relaxed.
 */

export const MODERATION_CATEGORIES = [
  'sexual_minors',
  'non_consensual_sexual',
  'sexual_explicit',
  'graphic_violence',
  'hate',
  'terrorism',
  'blocklist',
] as const;
export type ModerationCategory = (typeof MODERATION_CATEGORIES)[number];

export interface TermRule {
  category: ModerationCategory;
  terms: readonly string[];
}

export interface ComboRule {
  category: ModerationCategory;
  /** Maximum number of tokens between the two phrases. */
  window: number;
  a: readonly string[];
  b: readonly string[];
  /** Optional third set that must also be close to the matched `a` or `b` phrase. */
  c?: readonly string[];
}

/** Generic, safe-to-show explanations. They never repeat the prompt or the term that matched. */
export const CATEGORY_REASONS: Readonly<Record<ModerationCategory, string>> = {
  sexual_minors: 'Sexual content involving minors is not allowed.',
  non_consensual_sexual: 'Non-consensual or deepfake sexual content is not allowed.',
  sexual_explicit: 'Explicit sexual content is not allowed.',
  graphic_violence: 'Graphic gore is not allowed.',
  hate: 'Hateful content and incitement against people are not allowed.',
  terrorism: 'Terrorism-related content is not allowed.',
  blocklist: 'This prompt contains a term that is blocked on this service.',
};

// ---- Rules ----------------------------------------------------------------------------------

export const TERM_RULES: readonly TermRule[] = [
  {
    category: 'sexual_minors',
    terms: [
      'csam',
      'child porn',
      'child pornography',
      'kiddie porn',
      'kiddy porn',
      'underage porn',
      'underage sex',
      'loli',
      'shota',
      'lolicon',
      'shotacon',
      'loli porn',
      'اباحية اطفال',
    ],
  },
  {
    category: 'non_consensual_sexual',
    terms: [
      'deepnude',
      'nudify',
      'nudifier',
      'undress ai',
      'undress app',
      'revenge porn',
      'leaked nudes',
      'fake nude',
      'fake nudes',
      'deepfake porn',
      'deepfake nude',
      'deepfake nudes',
      'upskirt',
      'up skirt',
      'downblouse',
      'sexual assault',
      'non consensual',
      'nonconsensual',
      'forced sex',
      'date rape',
      'rape',
      'raped',
      'raping',
      'rapist',
      'molesting',
      'molested',
      'اغتصاب',
      'اغتصب',
      'مغتصب',
    ],
  },
  {
    category: 'sexual_explicit',
    terms: [
      'porn',
      'porno',
      'pornographic',
      'pornography',
      'pornstar',
      'porn star',
      'pron',
      'hentai',
      'xxx',
      'nsfw',
      'rule 34',
      'blowjob',
      'blow job',
      'handjob',
      'hand job',
      'footjob',
      'rimjob',
      'cumshot',
      'cum shot',
      'creampie',
      'gangbang',
      'gang bang',
      'bukkake',
      'orgy',
      'orgies',
      'milf',
      'sex scene',
      'sex tape',
      'sex act',
      'sex position',
      'sex toy',
      'sex video',
      'having sex',
      'have sex',
      'sexual intercourse',
      'intercourse',
      'fellatio',
      'cunnilingus',
      'masturbate',
      'masturbating',
      'masturbation',
      'anal sex',
      'oral sex',
      'genitals',
      'genitalia',
      'penis',
      'vagina',
      'vulva',
      'clitoris',
      'ejaculation',
      'orgasm',
      'dildo',
      'nude photo',
      'naked photo',
      'nude pic',
      'naked pic',
      'nude selfie',
      'nude video',
      'naked video',
      'sexually explicit',
      'explicit sexual',
      'explicit sex',
      'explicit content',
      'hardcore sex',
      'hardcore porn',
      'sex between',
      'naked sex',
      'nude sex',
      'threesome',
      'foursome',
      'doggystyle',
      'doggy style',
      'missionary position',
      'anal play',
      'anal beads',
      'anal plug',
      'butt plug',
      'anal intercourse',
      'anal penetration',
      'completely naked',
      'completely nude',
      'fully naked',
      'fully nude',
      'totally naked',
      'totally nude',
      'entirely naked',
      'entirely nude',
      'stark naked',
      'buck naked',
      'butt naked',
      'full frontal',
      'in the nude',
      ...SEX_ACT_AR,
      'سكس',
      'سيكس',
      'اباحي',
      'اباحية',
      'اباحيات',
      'اباحيين',
      'بورن',
      'بورنو',
      'هنتاي',
      'فيلم جنسي',
      'مشهد جنسي',
      'مشاهد جنسية',
      'مشاهد اباحية',
      'صور جنسية',
      'صورة جنسية',
      'مقاطع جنسية',
      'مقطع جنسي',
      'فيديو جنسي',
      'فيديوهات جنسية',
      'افلام جنسية',
      'افلام اباحية',
      'فيلم اباحي',
      'لقطات جنسية',
      'محتوى جنسي',
      'محتوى اباحي',
      'جنس صريح',
      'علاقة جنسية',
      'علاقات جنسية',
      'ممارسة جنسية',
      'جماع',
      // Nudity words that only describe people block on their own. "عاري" and "عارية" do not:
      // they also describe a bare tree or mountain and the idiom "عاري من الصحة" (baseless), so
      // they need a person, picture or pronoun word next to them (see the nudity combination).
      'عاريات',
      'عراة',
      'عريانة',
      'عريانات',
      'متعرية',
      'شرموطة',
      'قحبة',
      'عاهرة',
    ],
  },
  {
    category: 'graphic_violence',
    terms: [
      'gore',
      'gory',
      'dismember',
      'dismembered',
      'dismemberment',
      'decapitate',
      'decapitated',
      'decapitation',
      'behead',
      'beheaded',
      'beheading',
      'disembowel',
      'disemboweled',
      'disembowelled',
      'disembowelment',
      'severed head',
      'severed limb',
      'severed arm',
      'severed leg',
      'entrails',
      'mutilated',
      'mutilation',
      'torture porn',
      'snuff film',
      'snuff movie',
      'blood and guts',
      'skinned alive',
      'burned alive',
      'اشلاء',
      'احشاء',
      'تقطيع',
      'قطع الرأس',
      'قطع الرؤوس',
      'مقطوع الرأس',
      'بقر البطن',
      'التمثيل بالجثث',
    ],
  },
  {
    category: 'hate',
    terms: [
      'nigger',
      'nigga',
      'faggot',
      'wetback',
      'gook',
      'spic',
      'heil hitler',
      'sieg heil',
      'white power',
      'race war',
      // "women" is not a combination target: "women kill all the odds" is a figure of speech.
      'kill all women',
      'kill all the women',
      'kill every woman',
      'death to women',
      'death to all women',
      'exterminate women',
      'murder all women',
    ],
  },
  {
    category: 'terrorism',
    terms: [
      'join isis',
      'join daesh',
      'join al qaeda',
      'isis recruitment',
      'isis propaganda',
      'terrorist recruitment',
      'terrorist propaganda',
      'jihadist propaganda',
      'bomb making',
      'make a bomb',
      'build a bomb',
      'bomb making instructions',
      'suicide vest',
      'suicide bomber vest',
      'suicide bomber belt',
      'explosive belt',
      'pipe bomb',
      'nail bomb',
      'homemade bomb',
      'diy bomb',
      'improvised explosive',
      'ied',
      'make explosives',
      'making explosives',
      'build explosives',
      'building explosives',
      'homemade explosives',
      'how to make explosives',
      'mass shooting manifesto',
      'انضم الى داعش',
      'تجنيد ارهابيين',
      'صنع قنبلة',
      'صناعة المتفجرات',
      'صنع متفجرات',
      'تصنيع متفجرات',
      'تصنيع قنبلة',
      'عبوة ناسفة',
      'عبوات ناسفة',
      'سيارة مفخخة',
      'سيارات مفخخة',
      'دعاية داعش',
      'حزام ناسف',
    ],
  },
];

export const COMBO_RULES: readonly ComboRule[] = [
  {
    category: 'sexual_minors',
    window: 8,
    a: unique([...MINORS_EN, ...MINORS_AR]),
    b: unique([...SEXUAL_WIDE_EN, ...NUDITY_EN, ...SEXUAL_WIDE_AR, ...NUDITY_AR]),
  },
  {
    category: 'non_consensual_sexual',
    window: 6,
    a: [
      'deepfake',
      'deep fake',
      'face swap',
      'faceswap',
      'face swapped',
      'undress',
      'remove clothes',
      'remove her clothes',
      'remove his clothes',
      'remove their clothes',
      'take off clothes',
    ],
    b: ['nude', 'nudes', 'naked', 'nudity', 'porn', 'nsfw', 'sex', 'sexual', 'topless', 'explicit'],
  },
  {
    category: 'non_consensual_sexual',
    window: 6,
    a: SEXUAL_ACT_WORDS_EN,
    b: REAL_PERSON_CUES_EN,
  },
  {
    category: 'non_consensual_sexual',
    window: 6,
    a: ['ديب فيك', 'تعرية', 'ازالة الملابس'],
    b: ['صورة', 'صور', 'فيديو', 'مشهور', 'مشهورة', 'ممثلة', 'فنانة'],
  },
  // The canonical "undress this photo" requests of the image-to-image tool: an undress verb aimed
  // at a person or a photo, or clothing taken off someone, without needing a nudity word.
  {
    category: 'non_consensual_sexual',
    window: 4,
    a: ['undress', 'disrobe'],
    b: PERSON_CUES_EN,
  },
  {
    category: 'non_consensual_sexual',
    window: 4,
    a: GARMENT_OFF_EN,
    b: PERSON_CUES_EN,
  },
  {
    category: 'non_consensual_sexual',
    window: 4,
    a: REMOVE_VERBS_EN,
    b: GARMENTS_EN,
    c: PERSON_CUES_EN,
  },
  {
    category: 'non_consensual_sexual',
    window: 2,
    a: REMOVE_VERBS_AR,
    b: POSSESSED_GARMENTS_AR,
  },
  {
    category: 'non_consensual_sexual',
    window: 2,
    a: EDIT_VERBS_AR,
    b: NUDITY_AR,
  },
  // Nudity next to a person, a pronoun or a picture word: "naked woman", "make her naked",
  // "nude, 4k photo", "naked portrait". A nudity word on its own ("naked tree") stays harmless.
  {
    category: 'sexual_explicit',
    window: 5,
    a: unique([...NUDITY_EN, ...NUDITY_AR]),
    b: unique([...PEOPLE_EN, ...PEOPLE_AR, ...PRONOUNS_EN, ...ART_WORDS_EN, ...ART_WORDS_AR]),
  },
  // "topless" alone is also a car, a tower or a bar; next to a place people go topless it is not.
  {
    category: 'sexual_explicit',
    window: 5,
    a: ['topless'],
    b: TOPLESS_SETTINGS_EN,
  },
  {
    category: 'sexual_explicit',
    window: 4,
    a: ['fuck', 'fucked', 'fucking'],
    b: unique([...PRONOUNS_EN, ...PEOPLE_EN, 'sex', 'sexy', 'naked', 'nude', 'hard']),
  },
  {
    category: 'hate',
    window: 4,
    a: HATE_VERBS_EN,
    b: [...HATE_TARGETS_EN, ...HATE_TARGETS_EN_SINGULAR],
  },
  {
    category: 'hate',
    window: 4,
    a: HATE_VERBS_WEAK_EN,
    b: HATE_TARGETS_EN,
  },
  {
    category: 'hate',
    window: 3,
    a: HATE_VERBS_AR,
    b: [...HATE_TARGETS_AR, ...HATE_TARGETS_AR_SINGULAR],
  },
  {
    category: 'hate',
    window: 3,
    a: HATE_VERBS_WEAK_AR,
    b: HATE_TARGETS_AR,
  },
  {
    category: 'terrorism',
    window: 3,
    a: ['terrorist', 'terrorism', 'jihadist', 'isis', 'daesh', 'al qaeda'],
    b: ['recruitment', 'propaganda', 'manifesto', 'training manual', 'attack plan', 'instructions'],
  },
];

/**
 * Extra rules for requests that edit an uploaded photo (image-to-image, image-to-video). A real
 * person may be in that photo, so any nudity word is treated as an attempt to undress them.
 */
export const INPUT_IMAGE_TERM_RULES: readonly TermRule[] = [
  {
    category: 'non_consensual_sexual',
    terms: unique([...NUDITY_EN, ...NUDITY_AR, 'nudes', 'undress', 'disrobe']),
  },
];

/**
 * Well-known phrases that contain a blocked word but mean something else. They are removed from
 * the text before matching, so they never match on their own; a blocked word anywhere else in the
 * prompt still does.
 */
export const SAFE_PHRASES: readonly string[] = [
  'al gore',
  'gore tex',
  'gore vidal',
  'gore verbinski',
  'social intercourse',
  'spic and span',
  'spic n span',
  'rape of europa',
  'rape of the sabine women',
  'rape of proserpina',
  'rape of the lock',
  'beheading of john the baptist',
  'beheading of saint john',
  'judith beheading holofernes',
  'naked mole rat',
  'naked eye',
  'naked eyes',
  'naked cake',
  'naked truth',
  'nude lipstick',
  'nude lip',
  'nude lips',
  'nude makeup',
  'nude shade',
  'nude color',
  'nude colour',
  'nude tone',
  'nude tones',
  'nude heels',
  'nude pumps',
  'nude nails',
  'nude nail polish',
  'nude palette',
  'nude colored',
  'nude coloured',
  'nude toned',
  'nude pink',
  'nude beige',
  'naked tree',
  'naked trees',
  'naked branch',
  'naked branches',
  'naked flame',
  'naked flames',
  'naked bulb',
  'naked wire',
  'naked wires',
  'naked wall',
  'naked walls',
  'naked sword',
  'naked blade',
  'naked ambition',
  'naked rock',
  'naked cliff',
  'naked hill',
  'naked hills',
  'naked concrete',
  'topless car',
  'topless sports car',
  'topless roadster',
  'topless vehicle',
  'topless bus',
  'topless truck',
  'topless jeep',
  'topless convertible',
  'topless tower',
  'white power bank',
  'white power adapter',
  'white power supply',
  'white power cable',
  'white power plug',
  'white power strip',
  'white power outlet',
  'white power socket',
  'white power cord',
  'white power charger',
  'orgy of color',
  'orgy of colors',
  'orgy of colour',
  'orgy of colours',
  'orgy of light',
  'orgy of lights',
  'orgy of sound',
  'orgy of sounds',
  'orgy of flavor',
  'orgy of flavors',
  'orgy of flavour',
  'orgy of flavours',
  'orgy of destruction',
  'orgy of consumption',
  'orgy of spending',
  'oilseed rape',
  'rape field',
  'rape seed',
  'rape flower',
  'rape blossom',
  'rape plant',
  'rape crop',
  'rape oil',
  'cum laude',
  'david lynch',
  'dismembered robot',
  'dismembered doll',
  'dismembered mannequin',
  'dismembered statue',
  'baby doll',
  'baby blue',
  'baby pink',
];

/**
 * Ordinary pairs of short words that join into a rule word when someone spells it out with spaces
 * (`p e n i s`). Spelled-out joining is on purpose, so only pairs found in real sentences belong
 * here: "The pen is on the table" must not read as the anatomical word.
 */
export const NOT_SPELLED_OUT: readonly string[] = ['pen is'];
