import 'server-only';

/**
 * The built-in, deliberately modest moderation vocabulary (English and Arabic). Everything is
 * data: add a term by adding a string. Terms are written naturally (any case, Arabic with or
 * without diacritics) and normalized when compiled, so `نيك` and `نِيك` are the same entry.
 *
 * Matching is by whole token, never by substring, so "Essex", "grape" or "Scunthorpe" do not
 * trip "sex", "rape" or anything else. A multi-word entry is a phrase of adjacent tokens. English
 * entries also match their plural (`+s`/`+es`); Arabic entries also match with the common
 * one-letter clitics and the article attached (`و ف ب ك ل`, `ال`, `لل`).
 *
 * Two kinds of rule exist:
 * - a term rule blocks a phrase on its own;
 * - a combo rule blocks when a word of set `a` and a word of set `b` sit within `window` tokens
 *   of each other, which keeps ambiguous words ("naked", "child", "kill all") harmless on their
 *   own and harmful in context.
 *
 * Sexual content involving minors is the one category that is never relaxed.
 */

export const MODERATION_CATEGORIES = [
  'sexual_minors',
  'non_consensual_sexual',
  'sexual_explicit',
  'graphic_violence',
  'hate',
  'terrorism',
  'blocklist',
] as const;
export type ModerationCategory = (typeof MODERATION_CATEGORIES)[number];

export interface TermRule {
  category: ModerationCategory;
  terms: readonly string[];
}

export interface ComboRule {
  category: ModerationCategory;
  /** Maximum number of tokens between the two phrases. */
  window: number;
  a: readonly string[];
  b: readonly string[];
}

/** Generic, safe-to-show explanations. They never repeat the prompt or the term that matched. */
export const CATEGORY_REASONS: Readonly<Record<ModerationCategory, string>> = {
  sexual_minors: 'Sexual content involving minors is not allowed.',
  non_consensual_sexual: 'Non-consensual or deepfake sexual content is not allowed.',
  sexual_explicit: 'Explicit sexual content is not allowed.',
  graphic_violence: 'Graphic gore is not allowed.',
  hate: 'Hateful content and incitement against people are not allowed.',
  terrorism: 'Terrorism-related content is not allowed.',
  blocklist: 'This prompt contains a term that is blocked on this service.',
};

// ---- Shared vocabularies --------------------------------------------------------------------

const MINORS_EN = [
  'child',
  'children',
  'kid',
  'kiddie',
  'kiddy',
  'minor',
  'underage',
  'under age',
  'preteen',
  'pre teen',
  'tween',
  'toddler',
  'infant',
  'newborn',
  'preschooler',
  'schoolgirl',
  'schoolboy',
  'school girl',
  'school boy',
  'teen',
  'teenage',
  'teenager',
  'adolescent',
  'juvenile',
  'loli',
  'lolita',
  'shota',
  'little girl',
  'little boy',
  'young girl',
  'young boy',
  'small girl',
  'small boy',
];

const MINORS_AR = [
  'طفل',
  'طفلة',
  'اطفال',
  'قاصر',
  'قاصرات',
  'قاصرين',
  'مراهق',
  'مراهقة',
  'مراهقين',
  'مراهقات',
  'رضيع',
  'رضيعة',
  'تلميذة',
  'تلميذ',
  'بنت صغيرة',
  'ولد صغير',
  'فتاة صغيرة',
  'لوليتا',
];

const NUDITY_EN = [
  'nude',
  'nudity',
  'naked',
  'topless',
  'bottomless',
  'unclothed',
  'undressed',
  'bare breasts',
  'exposed breasts',
  'boobs',
  'nipples',
  'without clothes',
  'no clothes',
  'without underwear',
];

const NUDITY_AR = [
  'عاري',
  'عارية',
  'عاريات',
  'عراة',
  'عريان',
  'عريانة',
  'عريانات',
  'متعري',
  'متعرية',
  'تعري',
  'بدون ملابس',
  'بلا ملابس',
  'ثدي',
  'ثديين',
  'اثداء',
  'نهد',
  'نهود',
];

const PEOPLE_EN = [
  'woman',
  'women',
  'man',
  'men',
  'girl',
  'boy',
  'lady',
  'ladies',
  'female',
  'male',
  'person',
  'people',
  'body',
  'bodies',
  'model',
  'couple',
  'human',
  'figure',
  'celebrity',
  'actress',
  'actor',
  'teacher',
  'nurse',
  'student',
  'wife',
  'girlfriend',
  'mom',
  'mother',
  'sister',
  'bride',
];

const PEOPLE_AR = [
  'امرأة',
  'نساء',
  'بنت',
  'فتاة',
  'رجل',
  'ولد',
  'شاب',
  'شابة',
  'سيدة',
  'جسم',
  'اجساد',
  'شخص',
  'اشخاص',
  'ناس',
  'عارضة',
  'عارض',
  'زوجة',
  'ممثلة',
  'مشهورة',
];

// Words that make a minor-related prompt sexual. Wider than the explicit list on purpose.
const SEXUAL_WIDE_EN = [
  'sex',
  'sexy',
  'sexual',
  'sexually',
  'sexualized',
  'sexualised',
  'nsfw',
  'porn',
  'porno',
  'pornographic',
  'pornography',
  'erotic',
  'erotica',
  'seductive',
  'seduce',
  'sensual',
  'provocative',
  'lingerie',
  'fetish',
  'bdsm',
  'genitals',
  'genitalia',
  'penis',
  'vagina',
  'breasts',
  'orgasm',
  'masturbate',
  'masturbation',
  'cum',
  'hentai',
  'xxx',
  'explicit',
  'undress',
  'undressing',
  'striptease',
];

const SEXUAL_WIDE_AR = [
  'سكس',
  'سيكس',
  'جنسي',
  'جنسيا',
  'صور جنسية',
  'مشهد جنسي',
  'علاقة جنسية',
  'اباحي',
  'اباحية',
  'اباحيات',
  'بورن',
  'بورنو',
  'شهواني',
  'شهوانية',
  'مثيرة جنسيا',
  'ملابس داخلية',
  'اعضاء تناسلية',
  'قضيب',
  'مهبل',
  'فرج',
  'جماع',
];

const SEXUAL_ACT_WORDS_EN = [
  'sex',
  'sexual',
  'nsfw',
  'porn',
  'explicit',
  'orgasm',
  'nude',
  'nudes',
  'naked',
  'nudity',
  'topless',
];

const REAL_PERSON_CUES_EN = [
  'celebrity',
  'actress',
  'famous',
  'politician',
  'president',
  'my ex',
  'my neighbor',
  'my neighbour',
  'my teacher',
  'my boss',
  'my coworker',
  'my colleague',
  'my classmate',
  'my sister',
  'my mom',
  'my mother',
  'my friend',
  'my girlfriend',
  'my wife',
  'this photo',
  'this picture',
  'this image',
  'uploaded photo',
  'real person',
  'real people',
];

const HATE_TARGETS_EN = [
  'jews',
  'jewish people',
  'muslims',
  'christians',
  'hindus',
  'sikhs',
  'buddhists',
  'blacks',
  'black people',
  'whites',
  'white people',
  'arabs',
  'asians',
  'africans',
  'latinos',
  'mexicans',
  'gays',
  'lesbians',
  'trans people',
  'immigrants',
  'refugees',
  'women',
];

const HATE_TARGETS_AR = [
  'اليهود',
  'يهود',
  'المسلمين',
  'مسلمين',
  'المسيحيين',
  'النصارى',
  'الشيعة',
  'السنة',
  'الاكراد',
  'العرب',
  'السود',
  'المثليين',
  'الاجانب',
  'اللاجئين',
  'المهاجرين',
];

// ---- Rules ----------------------------------------------------------------------------------

export const TERM_RULES: readonly TermRule[] = [
  {
    category: 'sexual_minors',
    terms: [
      'csam',
      'child porn',
      'child pornography',
      'kiddie porn',
      'kiddy porn',
      'underage porn',
      'underage sex',
      'loli',
      'shota',
      'lolicon',
      'shotacon',
      'loli porn',
      'اباحية اطفال',
    ],
  },
  {
    category: 'non_consensual_sexual',
    terms: [
      'deepnude',
      'nudify',
      'nudifier',
      'undress ai',
      'undress app',
      'revenge porn',
      'leaked nudes',
      'fake nude',
      'fake nudes',
      'deepfake porn',
      'deepfake nude',
      'deepfake nudes',
      'upskirt',
      'up skirt',
      'downblouse',
      'sexual assault',
      'non consensual',
      'nonconsensual',
      'forced sex',
      'date rape',
      'rape',
      'raped',
      'raping',
      'rapist',
      'molesting',
      'molested',
      'اغتصاب',
      'اغتصب',
      'مغتصب',
    ],
  },
  {
    category: 'sexual_explicit',
    terms: [
      'porn',
      'porno',
      'pornographic',
      'pornography',
      'pornstar',
      'porn star',
      'pron',
      'hentai',
      'xxx',
      'nsfw',
      'rule 34',
      'blowjob',
      'blow job',
      'handjob',
      'hand job',
      'footjob',
      'rimjob',
      'cumshot',
      'cum shot',
      'creampie',
      'gangbang',
      'gang bang',
      'bukkake',
      'orgy',
      'orgies',
      'milf',
      'sex scene',
      'sex tape',
      'sex act',
      'sex position',
      'sex toy',
      'sex video',
      'having sex',
      'have sex',
      'sexual intercourse',
      'intercourse',
      'fellatio',
      'cunnilingus',
      'masturbate',
      'masturbating',
      'masturbation',
      'anal sex',
      'oral sex',
      'genitals',
      'genitalia',
      'penis',
      'vagina',
      'vulva',
      'clitoris',
      'ejaculation',
      'orgasm',
      'dildo',
      'nude photo',
      'naked photo',
      'nude pic',
      'naked pic',
      'nude selfie',
      'nude video',
      'naked video',
      'سكس',
      'سيكس',
      'اباحي',
      'اباحية',
      'اباحيات',
      'اباحيين',
      'بورن',
      'بورنو',
      'هنتاي',
      'فيلم جنسي',
      'مشهد جنسي',
      'صور جنسية',
      'مقاطع جنسية',
      'علاقة جنسية',
      'علاقات جنسية',
      'ممارسة الجنس',
      'ممارسة جنسية',
      'جماع',
      'شرموطة',
      'قحبة',
      'عاهرة',
    ],
  },
  {
    category: 'graphic_violence',
    terms: [
      'gore',
      'gory',
      'dismember',
      'dismembered',
      'dismemberment',
      'decapitate',
      'decapitated',
      'decapitation',
      'behead',
      'beheaded',
      'beheading',
      'disembowel',
      'disemboweled',
      'disembowelled',
      'disembowelment',
      'severed head',
      'severed limb',
      'severed arm',
      'severed leg',
      'entrails',
      'mutilated',
      'mutilation',
      'torture porn',
      'snuff film',
      'snuff movie',
      'blood and guts',
      'skinned alive',
      'burned alive',
      'اشلاء',
      'احشاء',
      'تقطيع',
      'قطع الرأس',
      'قطع الرؤوس',
      'مقطوع الرأس',
      'بقر البطن',
      'التمثيل بالجثث',
    ],
  },
  {
    category: 'hate',
    terms: [
      'nigger',
      'nigga',
      'faggot',
      'wetback',
      'gook',
      'spic',
      'heil hitler',
      'sieg heil',
      'white power',
      'race war',
    ],
  },
  {
    category: 'terrorism',
    terms: [
      'join isis',
      'join daesh',
      'join al qaeda',
      'isis recruitment',
      'isis propaganda',
      'terrorist recruitment',
      'terrorist propaganda',
      'jihadist propaganda',
      'bomb making',
      'make a bomb',
      'build a bomb',
      'bomb making instructions',
      'suicide vest',
      'how to make explosives',
      'mass shooting manifesto',
      'انضم الى داعش',
      'تجنيد ارهابيين',
      'صنع قنبلة',
      'صناعة المتفجرات',
      'دعاية داعش',
      'حزام ناسف',
    ],
  },
];

export const COMBO_RULES: readonly ComboRule[] = [
  {
    category: 'sexual_minors',
    window: 8,
    a: [...MINORS_EN, ...MINORS_AR],
    b: [...SEXUAL_WIDE_EN, ...NUDITY_EN, ...SEXUAL_WIDE_AR, ...NUDITY_AR],
  },
  {
    category: 'non_consensual_sexual',
    window: 6,
    a: [
      'deepfake',
      'deep fake',
      'face swap',
      'faceswap',
      'face swapped',
      'undress',
      'remove clothes',
      'remove her clothes',
      'remove his clothes',
      'remove their clothes',
      'take off clothes',
    ],
    b: ['nude', 'nudes', 'naked', 'nudity', 'porn', 'nsfw', 'sex', 'sexual', 'topless', 'explicit'],
  },
  {
    category: 'non_consensual_sexual',
    window: 6,
    a: SEXUAL_ACT_WORDS_EN,
    b: REAL_PERSON_CUES_EN,
  },
  {
    category: 'non_consensual_sexual',
    window: 6,
    a: ['ديب فيك', 'تعرية', 'ازالة الملابس'],
    b: ['صورة', 'صور', 'فيديو', 'مشهور', 'مشهورة', 'ممثلة', 'فنانة'],
  },
  {
    category: 'sexual_explicit',
    window: 5,
    a: [...NUDITY_EN, ...NUDITY_AR],
    b: [...PEOPLE_EN, ...PEOPLE_AR],
  },
  {
    category: 'hate',
    window: 3,
    a: [
      'kill all',
      'death to',
      'exterminate',
      'eradicate',
      'gas the',
      'wipe out',
      'hang the',
      'burn the',
      'lynch',
      'genocide of',
      'annihilate',
      'slaughter',
    ],
    b: HATE_TARGETS_EN,
  },
  {
    category: 'hate',
    window: 2,
    a: ['اقتلوا', 'اقتل', 'ابيدوا', 'ابادة', 'اذبحوا', 'الموت'],
    b: HATE_TARGETS_AR,
  },
  {
    category: 'terrorism',
    window: 3,
    a: ['terrorist', 'terrorism', 'jihadist', 'isis', 'daesh', 'al qaeda'],
    b: ['recruitment', 'propaganda', 'manifesto', 'training manual', 'attack plan', 'instructions'],
  },
];

/**
 * Well-known phrases that contain a blocked word but mean something else. They are removed from
 * the text before matching, so they never match on their own; a blocked word anywhere else in the
 * prompt still does.
 */
export const SAFE_PHRASES: readonly string[] = [
  'al gore',
  'gore tex',
  'gore vidal',
  'gore verbinski',
  'social intercourse',
  'spic and span',
  'spic n span',
  'rape of europa',
  'rape of the sabine women',
  'rape of proserpina',
  'rape of the lock',
  'beheading of john the baptist',
  'beheading of saint john',
  'judith beheading holofernes',
  'naked mole rat',
  'naked eye',
  'naked eyes',
  'naked cake',
  'naked truth',
  'nude lipstick',
  'nude lip',
  'nude lips',
  'nude makeup',
  'nude shade',
  'nude color',
  'nude colour',
  'nude tone',
  'nude tones',
  'nude heels',
  'nude pumps',
  'nude nails',
  'nude nail polish',
  'nude palette',
];
