import 'server-only';

/**
 * Shared word lists the rules in `terms.ts` are built from. Same conventions: written naturally,
 * normalized when compiled, English entries also match their plural, Arabic entries also match
 * with clitics and the article attached.
 */

export function unique(entries: readonly string[]): string[] {
  return [...new Set(entries)];
}

export const MINORS_EN = [
  'child',
  'children',
  'kid',
  'kiddie',
  'kiddy',
  'minor',
  'underage',
  'underaged',
  'under age',
  'preteen',
  'pre teen',
  'prepubescent',
  'pubescent',
  'tween',
  'toddler',
  'infant',
  'baby',
  'babies',
  'newborn',
  'preschooler',
  'schoolchild',
  'schoolchildren',
  'schoolgirl',
  'schoolboy',
  'school girl',
  'school boy',
  // "middle schooler", "high schooler", "8th grader", "fifth grader"
  'schooler',
  'highschooler',
  'grader',
  'elementary student',
  'elementary school student',
  'primary school student',
  'middle school student',
  'junior high student',
  'high school student',
  'high school girl',
  'high school boy',
  'middle school girl',
  'middle school boy',
  'teen',
  'teenage',
  'teenager',
  'adolescent',
  'juvenile',
  'youngster',
  'barely legal',
  'jailbait',
  'jail bait',
  'loli',
  'lolita',
  'shota',
  'little girl',
  'little boy',
  'young girl',
  'young boy',
  'young child',
  'small girl',
  'small boy',
  'small child',
  // Family roles: a "daughter" or "son" can be an adult, but sexual content with the word is not
  // something this service can tell apart from the child case.
  'daughter',
  'son',
  'niece',
  'nephew',
  'grandchild',
  'grandson',
  'granddaughter',
];

export const MINORS_AR = [
  'طفل',
  'طفلة',
  'اطفال',
  'قاصر',
  'قاصرات',
  'قاصرين',
  'مراهق',
  'مراهقة',
  'مراهقين',
  'مراهقات',
  'رضيع',
  'رضيعة',
  'تلميذة',
  'تلميذ',
  'بنت صغيرة',
  'ولد صغير',
  'فتاة صغيرة',
  'لوليتا',
  'صبي',
  'صبية',
  'ابنة',
  'ابنتي',
  'ابنتها',
  'ابنته',
  'ابنتهم',
  'بنتي',
  'بنتها',
  'بنته',
  'ابني',
  'ابنها',
  'ابنهم',
  'ولدي',
  'طفلتي',
  'طفلي',
  'طفلها',
  'اطفالي',
  'حفيد',
  'حفيدة',
];

export const NUDITY_EN = [
  'nude',
  'nudity',
  'naked',
  'topless',
  'bottomless',
  'unclothed',
  'undressed',
  'undressing',
  'disrobed',
  'disrobing',
  'bare breasts',
  'exposed breasts',
  'boobs',
  'nipples',
  'without clothes',
  'no clothes',
  'without underwear',
];

export const NUDITY_AR = [
  'عاري',
  'عارية',
  'عاريات',
  'عراة',
  'عريان',
  'عريانة',
  'عريانات',
  'متعري',
  'متعرية',
  'تعري',
  'بدون ملابس',
  'بلا ملابس',
  'ثدي',
  'ثديين',
  'اثداء',
  'نهد',
  'نهود',
];

/** Subject and object pronouns: "make her naked", "she is naked". */
export const PRONOUNS_EN = [
  'she',
  'her',
  'hers',
  'herself',
  'he',
  'him',
  'his',
  'himself',
  'they',
  'them',
  'their',
  'theirs',
  'themselves',
  'each other',
];

export const PEOPLE_EN = [
  'woman',
  'women',
  'man',
  'men',
  'girl',
  'boy',
  'lady',
  'ladies',
  'female',
  'male',
  'person',
  'people',
  'body',
  'bodies',
  'model',
  'couple',
  'human',
  'figure',
  'celebrity',
  'actress',
  'actor',
  'teacher',
  'nurse',
  'student',
  'wife',
  'husband',
  'girlfriend',
  'boyfriend',
  'mom',
  'mother',
  'dad',
  'father',
  'sister',
  'brother',
  'aunt',
  'uncle',
  'grandma',
  'grandmother',
  'grandpa',
  'grandfather',
  'cousin',
  'friend',
  'neighbor',
  'neighbour',
  'coworker',
  'colleague',
  'classmate',
  'boss',
  'bride',
];

export const PEOPLE_AR = [
  'امرأة',
  'نساء',
  'بنت',
  'فتاة',
  'رجل',
  'ولد',
  'شاب',
  'شابة',
  'سيدة',
  'جسم',
  'اجساد',
  'شخص',
  'اشخاص',
  'ناس',
  'عارضة',
  'عارض',
  'زوجة',
  'زوج',
  'ممثلة',
  'مشهورة',
  'اخت',
  'اخ',
  'ام',
  'اب',
  'جدة',
  'حبيبة',
  'صديقة',
  'جارة',
  'معلمة',
  'ممرضة',
  'طالبة',
];

/** Things a nude is "of" when no person is named: "nude, 4k photo", "naked portrait", "nude art". */
export const ART_WORDS_EN = [
  'photo',
  'photograph',
  'photography',
  'picture',
  'pic',
  'selfie',
  'portrait',
  'art',
  'artwork',
  'image',
  'video',
  'photoshoot',
  'shoot',
];

export const ART_WORDS_AR = [
  'صورة',
  'صور',
  'فيديو',
  'مقطع',
  'لوحة',
  'بورتريه',
  'فن',
  'رسم',
  'تصوير',
];

/** Places and settings that make "topless" about a person: "topless, beach". */
export const TOPLESS_SETTINGS_EN = [
  'beach',
  'pool',
  'sunbathing',
  'sunbathe',
  'sunbather',
  'tanning',
  'resort',
  'dancer',
  'waitress',
  'swimming',
  'yoga',
];

/** Arabic words for the sex act itself (the most common explicit verb, "نيك", included). */
export const SEX_ACT_AR = [
  'نيك',
  'نيكها',
  'نيكه',
  'نياك',
  'نياكة',
  'ينيك',
  'ينيكها',
  'انيك',
  'منيوك',
  'متناك',
  'ممارسة الجنس',
  'يمارس الجنس',
  'تمارس الجنس',
  'يمارسان الجنس',
  'يمارسون الجنس',
  'مارس الجنس',
  'مارسوا الجنس',
];

// Words that make a minor-related prompt sexual. Wider than the explicit list on purpose.
export const SEXUAL_WIDE_EN = [
  'sex',
  'sexy',
  'sexual',
  'sexually',
  'sexualized',
  'sexualised',
  'nsfw',
  'porn',
  'porno',
  'pornographic',
  'pornography',
  'erotic',
  'erotica',
  'seductive',
  'seduce',
  'sensual',
  'provocative',
  'lingerie',
  'fetish',
  'bdsm',
  'genitals',
  'genitalia',
  'penis',
  'vagina',
  'breasts',
  'orgasm',
  'masturbate',
  'masturbation',
  'cum',
  'hentai',
  'xxx',
  'explicit',
  'undress',
  'undressing',
  'striptease',
];

export const SEXUAL_WIDE_AR = [
  'سكس',
  'سيكس',
  'جنسي',
  'جنسيا',
  'صور جنسية',
  'مشهد جنسي',
  'علاقة جنسية',
  'اباحي',
  'اباحية',
  'اباحيات',
  'بورن',
  'بورنو',
  'شهواني',
  'شهوانية',
  'مثيرة جنسيا',
  'ملابس داخلية',
  'اعضاء تناسلية',
  'قضيب',
  'مهبل',
  'فرج',
  'جماع',
  ...SEX_ACT_AR,
];

export const SEXUAL_ACT_WORDS_EN = [
  'sex',
  'sexual',
  'nsfw',
  'porn',
  'explicit',
  'orgasm',
  'nude',
  'nudes',
  'naked',
  'nudity',
  'topless',
];

export const REAL_PERSON_CUES_EN = [
  'celebrity',
  'actress',
  'famous',
  'politician',
  'president',
  'my ex',
  'my neighbor',
  'my neighbour',
  'my teacher',
  'my boss',
  'my coworker',
  'my colleague',
  'my classmate',
  'my sister',
  'my mom',
  'my mother',
  'my friend',
  'my girlfriend',
  'my wife',
  'this photo',
  'this picture',
  'this image',
  'uploaded photo',
  'real person',
  'real people',
];

/** Who or what a piece of clothing is taken off: a pronoun, a person, or a photo of one. */
export const PERSON_CUES_EN = unique([
  ...PRONOUNS_EN,
  ...PEOPLE_EN,
  ...REAL_PERSON_CUES_EN,
  ...ART_WORDS_EN,
]);

export const REMOVE_VERBS_EN = [
  'remove',
  'removed',
  'removing',
  'take off',
  'took off',
  'taking off',
  'strip off',
  'stripped off',
  'stripping off',
  'rip off',
  'ripped off',
  'tear off',
  'tore off',
  'cut off',
  'pull off',
  'peel off',
  'erase',
  'delete',
];

export const GARMENTS_EN = [
  'clothes',
  'clothing',
  'dress',
  'top',
  'bra',
  'underwear',
  'panties',
  'bikini',
  'swimsuit',
  'lingerie',
  'undergarments',
  'garments',
  'outfit',
  'attire',
  'pants',
  'skirt',
  'shorts',
  'jeans',
];

export const GARMENT_OFF_EN = [
  'clothes off',
  'clothing off',
  'dress off',
  'bra off',
  'underwear off',
  'panties off',
  'bikini off',
  'swimsuit off',
];

/** Arabic "remove / strip" verbs and nouns, and garments that already say whose they are. */
export const REMOVE_VERBS_AR = [
  'ازل',
  'ازيل',
  'ازالة',
  'انزع',
  'انزعي',
  'نزع',
  'اخلع',
  'اخلعي',
  'خلع',
  'شيل',
  'جرد',
  'جردها',
  'جرده',
  'تجريد',
  'عري',
  'عريها',
  'عريه',
];

export const POSSESSED_GARMENTS_AR = [
  'ملابسها',
  'ملابسه',
  'ملابسهم',
  'ملابسهن',
  'ثيابها',
  'ثيابه',
  'ثيابهم',
  'لباسها',
  'لباسه',
  'فستانها',
  'بنطالها',
];

export const EDIT_VERBS_AR = [
  'اجعلها',
  'اجعله',
  'اجعلهم',
  'اجعلهن',
  'خليها',
  'خليه',
  'حولها',
  'حوله',
  'اظهرها',
  'اظهره',
  'ارسمها',
  'ارسمه',
];

// ---- Hate and terrorism ----------------------------------------------------------------------

// Groups are listed in the plural: "kill the black dragon" or "hang the Christian ornaments" are
// not about people, and an English noun listed in the plural does not match its singular.
export const HATE_TARGETS_EN = [
  'jews',
  'jewish people',
  'muslims',
  'christians',
  'hindus',
  'sikhs',
  'buddhists',
  'blacks',
  'black people',
  'whites',
  'white people',
  'arabs',
  'asians',
  'africans',
  'latinos',
  'mexicans',
  'gays',
  'lesbians',
  'trans people',
  'transgenders',
  'immigrants',
  'refugees',
  'migrants',
  'foreigners',
];

/** Religious nouns whose singular is still a person ("kill all muslim"); they match plurals too. */
export const HATE_TARGETS_EN_SINGULAR = ['jew', 'muslim', 'christian', 'hindu', 'sikh', 'buddhist'];

/** Verbs that mean violence on their own: any target near them is incitement. */
export const HATE_VERBS_EN = [
  'kill',
  'murder',
  'gas',
  'gassing',
  'lynch',
  'lynching',
  'exterminate',
  'eradicate',
  'annihilate',
  'slaughter',
  'massacre',
  'wipe out',
  'genocide of',
  'death to',
];

/** Verbs with ordinary uses ("hang a picture", "burn a candle"): only a plural group counts. */
export const HATE_VERBS_WEAK_EN = ['hang', 'hanging', 'burn'];

// Without the article: the matcher already accepts "ال", "لل" ("للعرب") and the one-letter clitics.
export const HATE_TARGETS_AR = [
  'يهود',
  'مسلمين',
  'مسيحيين',
  'نصاري',
  'اقباط',
  'شيعه',
  'السنة',
  'اكراد',
  'عرب',
  'سود',
  'مثليين',
  'اجانب',
  'لاجئين',
  'مهاجرين',
  'يزيديين',
  'دروز',
];

export const HATE_TARGETS_AR_SINGULAR = ['يهودي', 'مسلم', 'مسيحي'];

export const HATE_VERBS_AR = [
  'اقتلوا',
  'اقتل',
  'اقتلهم',
  'قتل',
  'ذبح',
  'اذبحوا',
  'اذبح',
  'ابيدوا',
  'ابادة',
  'تصفية',
  'الموت',
];

export const HATE_VERBS_WEAK_AR = ['احرقوا', 'احرق', 'حرق', 'اشنقوا', 'شنق', 'اعدام', 'اعدموا'];
